title: About
author: Ignacio Garrón
email: igarron@ub.edu
remote_theme: aterenin/minima-reboot
description: >


plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- CV.md
- research.md
- teaching.md
#- github.md

footer_icons:
- username: IgnacioGarron
  url: https://github.com/IgnacioGarron
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
