title: Personal website
author: Ignacio Garrón
email: igarron@ub.edu
remote_theme: aterenin/minima-reboot
description: >
Hello! My name is Ignacio, I am a Ph. D. Candidate in Economics and predoctoral fellow at Universitat de Barcelona (UB).
My fields of interests are applied finance and macroeconomics, forecasting, and machine learning, with special focus on forecasting risks in economics and finance.

Before joining the UB, I worked as a Senior Financial Analyst at the Central Bank of Bolivia (BCB), as an Economist at the Center for Latin American Monetary Studies (CEMLA), and as a Junior Researcher at the Instituto de Investigaciones Socioeconómicas - Universidad Católica Boliviana.

https://github.com/IgnacioGarron


plugins:
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-feed
  - jekyll-redirect-from

minima_reboot:
  date_format: "%b %-d, %Y"
  date_format_short: "%b %-d"

header_pages:
- about.md
- publications.md
- github.md

footer_icons:
- username: IgnacioGarron
  url: https://github.com/IgnacioGarron
  icon: icon-github.svg

paginate: 5

markdown: kramdown

exclude:
  - Gemfile
  - Gemfile.lock
  - minima-reboot.gemspec
